name: Publish Vocabulary Workflow from csv

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      version:
        required: false
        type: string
      namespace_label:
        required: true
        type: string
      namespace:
        required: true
        type: string
      mappings_file:
        required: true
        type: string
      
    secrets:
        token:
          required: true
          
jobs:
  csv-to-skos:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
      
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          token: ${{ secrets.token }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install pip dependencies
        run: pip install skosify

      - name: Convert YARRRML to RML
        uses: vemonet/yarrrml-parser@v1.1
        with:
          input: ${{ inputs.mappings_file }}
          output: mappings.rml.ttl
          
      - name: Run RML mapper
        uses: vemonet/rmlmapper-java@v4.9.0
        with:
          mapping: mappings.rml.ttl
          output: linked_data.rdf.ttl
          serialization: turtle
        env:
          JAVA_OPTS: "-Xmx6g"

      - name: Run skosify
        run: |
          skosify linked_data.rdf.ttl -o voc.skos.ttl \
            --label "${{ inputs.namespace_label}}" \
            --namespace "${{ inputs.namespace}}" \
            --set-modified \
            -l en

      - name: Upload vocabulary
        uses: actions/upload-artifact@v4
        with:
          name: voc-from-csv.skos.ttl
          path: ./voc.skos.ttl

      - name: Publish  
        if: github.event_name == 'release'
        uses: ./.github/workflows/skosmos_upload.yml
        with:
          artifact: voc-from-csv.skos.ttl
          token: ${{ secrets.GITHUB_TOKEN }}
