name: Test Publish Vocabulary Workflow

on:
    push:
        branches:
            - main
    pull_request:


jobs:
    test-workflow:
        uses: ./.github/workflows/csv2skos.yml
        with:
            namespace: http://www.example.com/
            namespace_label: example

